CREATE TABLE TB_AGENDAMENTO (
    ID SERIAL PRIMARY KEY,
    TITULO VARCHAR(120) NOT NULL,
    DESCRICAO TEXT,
    DATAINICIO TIMESTAMP NOT NULL,
    DATAFIM TIMESTAMP NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'AGENDADO',
    USUARIO VARCHAR(80) NOT NULL,
    CRIADOEM TIMESTAMP NOT NULL DEFAULT NOW(),
    ATUALIZADOEM TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT CK_STATUS CHECK (STATUS IN ('AGENDADO', 'CANCELADO', 'CONCLUIDO')),
    CONSTRAINT CK_INTERVALO CHECK (DATAINICIO < DATAFIM)
);