CREATE OR REPLACE FUNCTION SET_ATUALIZADO_EM()
RETURNS TRIGGER AS $$
BEGIN
    NEW.ATUALIZADOEM := NOW();
    RETURN NEW;
END
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_SET_ATUALIZADO_EM
    BEFORE UPDATE
    ON TB_AGENDAMENTO
    FOR EACH ROW
EXECUTE FUNCTION SET_ATUALIZADO_EM();